services:
  postgres:
    image: postgres:17-alpine
    container_name: authingo-postgres
    environment:
      POSTGRES_USER: "${DB_USER:-postgres-healthcheck}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_DB: "${DB_NAME:-postgres-healthcheck}" 
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
